import assert from 'node:assert/strict';
import fs from 'node:fs';
import {compile} from '@vue/compiler-dom';
import FitnessForm from '../src/components/FitnessForm.js';
import {normalizeFitness,calculateBMI,saveFitnessProfile,readLocalObject} from '../src/utils/fitness.js';
import {normalizeBackup} from '../src/utils/backup.js';
const values=new Map();
const storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const draft={name:'Test user',username:'test_user',email:'sample@gmail.com',heightCm:'180',weightKg:'81',daysPerWeek:'3',sex:'Prefer not to say',experience:'New to exercise',goal:'Build strength',equipment:'Bodyweight only'};
const saved=saveFitnessProfile(storage,{bio:'Keep bio',avatarUrl:'existing'}, {theme:'dark'},draft);
assert.equal(saved.profile.fitness.heightCm,180);assert.equal(calculateBMI(saved.profile.fitness),'25.0');assert.equal(saved.profile.bio,'Keep bio');assert.equal(saved.profile.onboardingComplete,true);assert.deepEqual(readLocalObject(storage,'pulse_user_profile'),saved.profile);
assert.equal(calculateBMI({}),'—');assert.equal(normalizeFitness({}).heightCm,null);
assert.throws(()=>normalizeFitness({heightCm:-1}),/height/);assert.throws(()=>normalizeFitness({daysPerWeek:1.5}),/days/);assert.throws(()=>saveFitnessProfile(storage,{}, {}, {...draft,name:''}),/name/);
const current={...saved,routines:[],sharedRoutines:[],history:[],achievements:{}};
assert.deepEqual(normalizeBackup({version:2,profile:saved.profile},current).profile,saved.profile);
assert.throws(()=>normalizeBackup({profile:{fitness:{sex:'invalid'}}},current),/sex/);
const before=new Map(values);let calls=0;
assert.throws(()=>saveFitnessProfile({...storage,setItem(k,v){if(++calls===2)throw Error('quota');storage.setItem(k,v);}},saved.profile,saved.settings,{...draft,name:'Changed'}),/Could not save/);assert.deepEqual(values,before);
compile(FitnessForm.template);
const html=fs.readFileSync(new URL('../login.html',import.meta.url),'utf8');compile(html.split('<main')[1].replace(/^[^>]*>/,'').split('</main>')[0]);
console.log('PASS: fitness setup persistence, validation, BMI, optional fields, backup round-trip, rollback, and entry/form template compilation.');
// Exercise real step transitions: invalid input blocks, Back keeps answers, save occurs only at the end.
let allow = false, emitted = null;
const wizard = FitnessForm.setup({stepped:true,profile:{},settings:{}},{emit:(name,value)=>{emitted=value;}});
wizard.form.value = {querySelectorAll:()=>[{reportValidity:()=>allow}]};
wizard.draft.value = {...draft};
wizard.save();assert.equal(wizard.step.value,0);assert.equal(emitted,null);
allow=true;wizard.save();assert.equal(wizard.step.value,1);assert.equal(emitted,null);
wizard.goBack();assert.equal(wizard.step.value,0);assert.equal(wizard.draft.value.name,draft.name);
wizard.save();wizard.save();assert.equal(wizard.step.value,2);assert.equal(emitted,null);
globalThis.localStorage=storage;wizard.save();assert.equal(emitted.profile.fitness.goal,draft.goal);delete globalThis.localStorage;
console.log('PASS: grouped setup validation, forward/back navigation, retained answers and final-step persistence.');
