import { initState } from './features/state.js';
import { initCatalog } from './features/catalog.js';
import { initMetrics } from './features/metrics.js';
import { initStorage } from './features/storage.js';
import { initSettings } from './features/settings.js';
import { initProfile } from './features/profile.js';
import { initRoutines } from './features/routines.js';
import { initTimer } from './features/timer.js';
import { initLifecycle } from './features/lifecycle.js';

/** Assemble features inside Vue setup; lifecycle hooks start only after every action exists. */
export function createPulseApp() {
  const ctx = {};
  initState(ctx);
  initCatalog(ctx);
  initMetrics(ctx);
  initStorage(ctx);
  initSettings(ctx);
  initProfile(ctx);
  initRoutines(ctx);
  initTimer(ctx);
  initLifecycle(ctx);
  return {
  pendingProfileEdit: ctx.pendingProfileEdit,
  confirmProfileEdit: ctx.confirmProfileEdit,
  cancelProfileEdit: ctx.cancelProfileEdit,
  cycleProfileConfirmFocus: ctx.cycleProfileConfirmFocus,
  onFitnessSaved: ({profile, settings}) => {ctx.userProfile.value = profile; ctx.userSettings.value = settings;},
  detailExercise: ctx.detailExercise,
  openExerciseDetails: ctx.openExerciseDetails,
  closeExerciseDetails: ctx.closeExerciseDetails,
  handleDetailKeys: ctx.handleDetailKeys,
  catalog: ctx.catalog,
  libraryTab: ctx.libraryTab,
  librarySearch: ctx.librarySearch,
  libraryEquipment: ctx.libraryEquipment,
  libraryMuscle: ctx.libraryMuscle,
  libraryPage: ctx.libraryPage,
  libraryPages: ctx.libraryPages,
  libraryMatches: ctx.libraryMatches,
  libraryItems: ctx.libraryItems,
  equipmentOptions: ctx.equipmentOptions,
  muscleOptions: ctx.muscleOptions,
  selectedLibraryExercise: ctx.selectedLibraryExercise,
  addCatalogToRoutine: ctx.addCatalogToRoutine,
  linkIllustration: ctx.linkIllustration,
  exerciseSearch: ctx.exerciseSearch,
  exerciseResults: ctx.exerciseResults,
  exerciseAsset: ctx.exerciseAsset,
  attachExercise: ctx.attachExercise,
  notice: ctx.notice,
  restoreBusy: ctx.restoreBusy,
  toggleReminders: ctx.toggleReminders,
  skipPreparation: ctx.skipPreparation,
  ALL_DAYS: ctx.ALL_DAYS,
  ALL_INTERESTS: ctx.ALL_INTERESTS,
  toggleDaySelection: ctx.toggleDaySelection,
  setSchedulePreset: ctx.setSchedulePreset,
  activeTab: ctx.activeTab,
  showProfileView: ctx.showProfileView,
  showSettingsView: ctx.showSettingsView,
  showCancelModal: ctx.showCancelModal,
  showRoutineModal: ctx.showRoutineModal,
  showCropModal: ctx.showCropModal,
  showSharePickerModal: ctx.showSharePickerModal,
  showInterestSelector: ctx.showInterestSelector,
  showReportModal: ctx.showReportModal,
  showPrivacyModal: ctx.showPrivacyModal,
  settingCategories: ctx.settingCategories,
  settingsCategory: ctx.settingsCategory,
  problemDescription: ctx.problemDescription,
  jsonFileInput: ctx.jsonFileInput,
  userProfile: ctx.userProfile,
  userSettings: ctx.userSettings,
  calculatedBMI: ctx.calculatedBMI,
  isEditingName: ctx.isEditingName,
  tempName: ctx.tempName,
  avatarError: ctx.avatarError,
  isEditingUsername: ctx.isEditingUsername,
  tempUsername: ctx.tempUsername,
  isEditingBio: ctx.isEditingBio,
  tempBio: ctx.tempBio,
  profileTab: ctx.profileTab,
  sharedRoutines: ctx.sharedRoutines,
  workoutHistory: ctx.workoutHistory,
  weeklyActivityChart: ctx.weeklyActivityChart,
  weeklyTotalMinutes: ctx.weeklyTotalMinutes,
  chartPoints: ctx.chartPoints,
  svgLinePath: ctx.svgLinePath,
  svgAreaPath: ctx.svgAreaPath,
  userAchievements: ctx.userAchievements,
  startEditUsername: ctx.startEditUsername,
  saveUsername: ctx.saveUsername,
  startEditBio: ctx.startEditBio,
  saveBio: ctx.saveBio,
  toggleInterest: ctx.toggleInterest,
  openShareRoutinePicker: ctx.openShareRoutinePicker,
  publishRoutine: ctx.publishRoutine,
  unshareRoutine: ctx.unshareRoutine,
  copyPublicRoutine: ctx.copyPublicRoutine,
  rawImageSrc: ctx.rawImageSrc,
  cropZoom: ctx.cropZoom,
  cropOffsetX: ctx.cropOffsetX,
  cropOffsetY: ctx.cropOffsetY,
  fileInput: ctx.fileInput,
  cropCanvasRef: ctx.cropCanvasRef,
  routines: ctx.routines,
  editingRoutine: ctx.editingRoutine,
  currentRoutine: ctx.currentRoutine,
  currentExerciseIndex: ctx.currentExerciseIndex,
  currentExercise: ctx.currentExercise,
  currentSet: ctx.currentSet,
  timerState: ctx.timerState,
  pausedPreviousState: ctx.pausedPreviousState,
  displaySeconds: ctx.displaySeconds,
  stats: ctx.stats,
  nextUpText: ctx.nextUpText,
  ringDashOffset: ctx.ringDashOffset,
  stateStrokeColor: ctx.stateStrokeColor,
  startWorkout: ctx.startWorkout,
  completeSet: ctx.completeSet,
  skipRest: ctx.skipRest,
  pauseTimer: ctx.pauseTimer,
  resumeTimer: ctx.resumeTimer,
  restartSet: ctx.restartSet,
  confirmCancelWorkout: ctx.confirmCancelWorkout,
  confirmEndWorkout: ctx.confirmEndWorkout,
  openCreateRoutineModal: ctx.openCreateRoutineModal,
  editRoutine: ctx.editRoutine,
  duplicateRoutine: ctx.duplicateRoutine,
  confirmDeleteRoutine: ctx.confirmDeleteRoutine,
  addExerciseToRoutine: ctx.addExerciseToRoutine,
  removeExerciseFromRoutine: ctx.removeExerciseFromRoutine,
  saveRoutine: ctx.saveRoutine,
  startEditName: ctx.startEditName,
  saveName: ctx.saveName,
  triggerAvatarFileSelect: ctx.triggerAvatarFileSelect,
  onAvatarFileSelected: ctx.onAvatarFileSelected,
  renderCropPreview: ctx.renderCropPreview,
  startCropDrag: ctx.startCropDrag,
  startCropDragTouch: ctx.startCropDragTouch,
  onCropDrag: ctx.onCropDrag,
  onCropDragTouch: ctx.onCropDragTouch,
  stopCropDrag: ctx.stopCropDrag,
  applyCroppedAvatar: ctx.applyCroppedAvatar,
  exportDataJSON: ctx.exportDataJSON,
  triggerRestoreJSONSelect: ctx.triggerRestoreJSONSelect,
  onRestoreJSONSelected: ctx.onRestoreJSONSelected,
  submitReport: ctx.submitReport,
  confirmSignOut: ctx.confirmSignOut,
  unblockUser: ctx.unblockUser,
  resetApplicationData: ctx.resetApplicationData,
  saveSettingsToStorage: ctx.saveSettingsToStorage,
  saveProfileToStorage: ctx.saveProfileToStorage,
  formatSeconds: ctx.formatSeconds,
  formatDurationWords: ctx.formatDurationWords
};
}
